quality/urls.py
from django.conf.urls.defaults import patterns, url
#from cartography.models import Document
#from cartography.views import documentdetail,newmaptpl,upload_document

#info_dict = {
#	'queryset': Document.objects.all(),
#	}

#urlpatterns = patterns('',
#	(r'^(?P<docid>\d+)$', documentdetail),
 #   (r'^upload/(?P<mapid>\d+)/?$', upload_document),
#	url(r'^upload/?$', 'cartography.views.upload_document', name='document-upload'),
#	(r'^newmap$', newmaptpl),
#)
urlpatterns = patterns('',
    url(r'^subtopics/','quality.views.listSubtopics'),
    url(r'^ask4weights/','quality.views.ask4weights'),
	url(r'^weights/','quality.views.calculateBest')
)

quality/models.py
from django.db import models
from geonode.maps.models import Map, Layer
from django.db.models import signals
import os

#class Document(models.Model):
#	"""

#	A document is any kind of information that can be attached to a map such as pdf, images, videos, xls...

#	"""

#	title = models.CharField(max_length=255)
#	maps = models.ManyToManyField(Map)
#	file = models.FileField(upload_to='documents')
#	type = models.CharField(max_length=128,blank=True,null=True)

#	def __unicode__(self):
#		return self.title

#	@models.permalink
#	def get_absolute_url(self):
#		return self.file.url

#def pre_save_document(instance, sender, **kwargs):
#	base_name, extension = os.path.splitext(instance.file.name)
#	instance.type=extension[1:]

#signals.pre_save.connect(pre_save_document, sender=Document)

# this model contains the results of the data quality assessment that has been
# performed as an activity of the GMES project
class QualityMatrix(models.Model):
    layer = models.OneToOneField(Layer)
    geographicExtent = models.IntegerField('Geographic Extent')
    licensingConstraint = models.IntegerField('Licensing and Constraint')
    scaleDenominator = models.IntegerField('Scale Denominator')
    update = models.IntegerField('Update')
    temporalExtent = models.IntegerField('Temporal Extent')
    fitness4Use = models.IntegerField('Fitness for Use')
    thematicRichness = models.IntegerField('Thematic Richness')
    integration = models.IntegerField('Integration')
    dataIntegrity = models.IntegerField('Data Integrity')
    positionalAccuracy = models.IntegerField('Positional Accuracy')
    thematicAccuracy = models.IntegerField('Thematic Accuracy')
    completeness = models.IntegerField('Completeness')

    def __unicode__(self):
        return "bravo"

class Subtopic(models.Model):
    title = models.CharField(max_length=100)

class LayerSubtopic(models.Model):
    layer = models.OneToOneField(Layer)
    subtopic = models.ForeignKey(Subtopic, verbose_name="the related subtopic")

quality/templates/quality/ask4weights.html
{% extends "page_layout.html" %}
{% load i18n %}

{% block title %} {% trans "Browse Data" %} - {{ block.super }} {% endblock %}

{% block head %}
{% include "geonode/ext_header.html" %}
{% include "geonode/app_header.html" %}
{{ block.super }}
<script type="text/javascript">
Ext.onReady(function(){
{% autoescape off %}
  var submitForm = function() {
      Ext.query('#search_form form')[0].submit();
  };
  var searchButton = new Ext.Button({renderTo: 'submit_search', text: '{% trans "Search" %}',
                                     handler: submitForm});
  var searchInput = new Ext.form.TextField({applyTo: 'search_query', width: 350});
	
	var goButton = new Ext.Button({
		renderTo: 'ask_weights',
		text: 'Go!',
		handler: function(){window.location = "{%url geonode.maps.views.maps_search_page%}";}
	});
{% endautoescape %}
});
</script>
{% endblock %}

{% block main %}
<div class="twocol">
	<h2>{{subtopic.title}}</h2>
	<p>Please define your own weights between 0 and 10!</p>
	<p>When you're done, press the "Calculate" button in order to get the dataset with best quality</p>
	<form action="/quality/weights" method="GET">
		<fieldset>
			<legend>Quality Indicators:</legend>
				<table>
				<tr>
					<td>Geographic Extent</td>
					<td><input type="text" size=3 name="geographicExtent" value=0></td>
				</tr>
				<tr>
					<td>Licensing and Constraints  </td>
					<td><input type="text" size=3 name="licensingConstraint" value=0></td>
				</tr>
				<tr>
					<td>Scale Denominator</td>
					<td><input type="text" size=3 name="scaleDenominator" value=0></td>
				</tr>
				<tr>
					<td>Update</td>
					<td><input type="text" size=3 name="update" value=0></td>
				</tr>
				<tr>
					<td>Temporal Extent</td>
					<td><input type="text" size=3 name="temporalExtent" value=0></td>
				</tr>
				<tr>
					<td>Fitness for Use</td>
					<td><input type="text" size=3 name="fitness4use" value=0></td>
				</tr>
				<tr>
					<td>Thematic Richness</td>
					<td><input type="text" size=3 name="thematicRichness" value=0></td>
				</tr>
				<tr>
					<td>Integration</td>
					<td><input type="text" size=3 name="integration" value=0></td>
				</tr>
				<tr>
					<td>Data Integrity</td>
					<td><input type="text" size=3 name="dataIntegrity" value=0></td>
				</tr>
				<tr>
					<td>Positional Accuracy</td>
					<td><input type="text" size=3 name="positionalAccuracy" value=0></td>
				</tr> 
				<tr>
					<td>Thematic Accuracy</td>
					<td><input type="text" size=3 name="thematicAccuracy" value=0></td>
				</tr>
				<tr>
					<td>Completeness</td>
					<td><input type="text" size=3 name="completeness" value=0></td>
				</tr> 
				<tr>
					<td>The subtopic code is</td>
					<td><input type="text" size=3 name="subtopic_pk" value ={{subtopic.pk}} readonly="readonly"></td>
				</tr>
			</table>
			<br>
			<input type="submit" value="Calculate!">
		</fieldset>
	</form>
<!--	<table>
		<tr>
			<td>
				<p>Scale Denominator</p>
			</td>
			<td>
				<input type="text"/>
			</td>
		</tr>
		<tr>
			<td>
				<p>Geographic Extent</p>
			</td>
			<td>
				<input type="text"/>
			</td>
		</tr>
		<tr><td>...</td></tr>
	</table>-->
</div>

{% endblock %}

{% block sidebar %}
  {% block sidebar_info %}    
  {% endblock %}

{% endblock %}

quality/templates/quality/layer.html
{% extends "page_layout.html" %}
{% load geonode_auth %}
{% load i18n %}

{% block title %} {{ layer.resource.title|default:layer.typename }} - {{ block.super }} {% endblock %}

{% block head %}
{% include "geonode/ext_header.html" %}
{% include "geonode/app_header.html" %}
{% include "geonode/geo_header.html" %}

<link rel="stylesheet" type="text/css" href="{{ GEONODE_CLIENT_LOCATION }}theme/ux/colorpicker/color-picker.ux.css" />

{{ block.super }}

    <script type="text/javascript">
{% autoescape off %}
        var styleEditor, modified = false;
        Ext.onReady(function() {
            var config = {
                tools: [{
                    ptype: "gxp_wmsgetfeatureinfo",
                    // uncomment the line below if you want feature info in a grid
                    //format: "grid",
                    actionTarget: "main.tbar",
                    outputConfig: {width: 400, height: 200, panIn: false}
                }],
                proxy: "/proxy/?url=",
                localGeoServerBaseUrl: "{{GEOSERVER_BASE_URL}}",
                authorizedRoles: "{{ user.is_authenticated|yesno:"ROLE_ADMINISTRATOR,ROLE_ANONYMOUS" }}",

                /* The URL to a REST map configuration service.  This service 
                 * provides listing and, with an authenticated user, saving of 
                 * maps on the server for sharing and editing.
                 */
                rest: "/maps/",
                
                portalConfig: {
                    renderTo: "preview_map",
                    height: 350
                },

                createTools: function() {
                    return [new Ext.Button({
                        tooltip: GeoExplorer.prototype.backgroundContainerText,
                        iconCls: 'icon-layer-switcher',
                        menu: new gxp.menu.LayerMenu({
                            layers: this.mapPanel.layers
                        })
                    })]
                },
                listeners: {
                    "ready": function() {
                        var map = app.mapPanel.map;
                        map.zoomToExtent(map.layers.slice(-1)[0].maxExtent);
                    },
                    "beforeunload": function() {
                        if (modified) {
                            styleEditor.show();
                            return false;
                        }
                    }
                }
            };

            config = Ext.apply(config, {{ viewer|safe }});

            app = new GeoExplorer.Viewer(config);
            
            Ext.get(Ext.DomQuery.select("input[@name='style']")).on("click", function(evt, elem) {
                app.selectedLayer.getLayer().mergeNewParams({
                    "STYLES": elem.value,
                    "_dc": Math.random()
                });
            });

            Ext.get(Ext.DomQuery.select("select[@name='default-style']")).on("change", function(evt, elem) {
                Ext.Ajax.request({
                    method: "post",
                    url: "?style",
                    params: {"defaultStyle" : elem.value}
                });
            });
{% has_obj_perm user layer "maps.change_layer" as can_change %}
{% if can_change %}
            Ext.get(Ext.DomQuery.select(".style-title")).on("click", function(evt, elem) {
                showStyle(Ext.get(elem).prev("input").getAttribute("value"));
            });
{% endif %}

{% has_obj_perm user layer "maps.change_layer_permissions" as can_change_permissions %}
{% if can_change_permissions %}
            new GeoNode.PermissionsEditor({
                renderTo: "permissions_form",
                userLookup: "{% url geonode.views.ajax_lookup %}",
                permissions: {{ permissions_json }},
                levels: {
                    'admin': 'layer_admin',
                    'readwrite': 'layer_readwrite',
                    'readonly': 'layer_readonly',
                    '_none': '_none'
                },
                listeners: {
                    updated: function(perms) {
                        var submitTo = "{% url geonode.maps.views.ajax_layer_permissions layer.typename %}";
                        Ext.Ajax.request({ url: submitTo, jsonData: perms.writePermissions() });
                    }
                }
            });
{% endif %}
        });

        function showStyle(styleName) {
            
            if (!styleName) {
                Ext.ComponentMgr.all.on("add", function(index, object) {
                    if (object instanceof gxp.WMSStylesDialog) {
                        Ext.ComponentMgr.all.un("add", arguments.callee);
                        object.on("ready", function() {
                            object.addStyle();
                        }, this, {single: true});
                    }
                });
            }
            app.tools["styler"].actions[0].execute();
        }
{% endautoescape %}
    </script>
{% endblock %}

{% block main %}
<div class="twocol">
	<div id="description"> <h3> {{ layer.resource.title|default:layer.typename }} </h3> </div>
	<p> <strong>{% trans "Abstract" %}:</strong> {{ layer.abstract|default:_("No abstract for this layer.") }} </p>

	<div id="preview_map"></div>

	<p><strong>GMES Quality Assessment Results</strong></p>

	<table border="5" frame="vsides">
		<tr>
			<th>Indicator</th>
			<th>Score</th>
		</tr>
		<tr>
			<td>Geographic Extent</td>
			<td align='center'>{{qualityRecord.geographicExtent}}</td>
		</tr>
		<tr>
			<td>Licensing and Constraints</td>
			<td align='center'>{{qualityRecord.licensingConstraint}}</td>
		</tr>
		<tr>
			<td>Scale Denominator</td>
			<td align='center'>{{qualityRecord.scaleDenominator}}</td>
		</tr>
		<tr>
			<td>Update</td>
			<td align='center'>{{qualityRecord.update}}</td>
		</tr>
		<tr>
			<td>Temporal Extent</td>
			<td align='center'>{{qualityRecord.temporalExtent}}</td>
		</tr>
		<tr>
			<td>Fitness for Use</td>
			<td align='center'>{{qualityRecord.fitness4Use}}</td>
		</tr>
		<tr>
			<td>Thematic Richness</td>
			<td align='center'>{{qualityRecord.thematicRichness}}</td>
		</tr>
		<tr>
			<td>Integration</td>
			<td align='center'>{{qualityRecord.integration}}</td>
		</tr>
		<tr>
			<td>Data Integrity</td>
			<td align='center'>{{qualityRecord.dataIntegrity}}</td>
		</tr>
		<tr>
			<td>Positional Accuracy</td>
			<td align='center'>{{qualityRecord.positionalAccuracy}}</td>
		</tr>
		<tr>
			<td>Thematic Accuracy</td>
			<td align='center'>{{qualityRecord.thematicAccuracy}}</td>
		</tr>
		<tr>
			<td>Completeness</td>
			<td align='center'>{{qualityRecord.completeness}}</td>
		</tr>
	</table>

{% if layer.display_type %}<p> <strong>{% trans "Type" %}:</strong> {{ layer.display_type }} </p>{% endif %}
{% if layer.keywords %}<p> <strong>{% trans "Keywords" %}:</strong> {{ layer.keywords }}</p>{% endif %}
{% if layer.edition %}<p> <strong>{% trans "Edition" %}:</strong> {{ layer.edition }}</p>{% endif %}
{% if layer.topic_category %}<p> <strong>{% trans "Topic Category" %}:</strong> {{ layer.topic_category }}</p>{% endif %}

{% if layer.constraints_use or layer.constraints_other %}
<p> <strong>{% trans "Citation" %}:</strong> 
    {{ layer.constraints_use}} {{ layer.contraints_other}}
</p>
{% endif %}

{% if layer.owner %}
<p> <strong>{% trans "Owner" %}:</strong>
    <a href="{{ layer.owner.get_profile.get_absolute_url }}"> {{ layer.owner.username }} </a>
</p>
{% endif %}

{% if layer.poc %}
<p> <strong>{% trans "Point of Contact" %}:</strong>
  {% if layer.poc.user %}
    <a href="{{ layer.poc.user.get_profile.get_absolute_url }}"> {{ layer.poc.user.username }} </a>
  {% else %}
    <ul>
        {% if layer.poc.name %}<li><strong>{% trans "Name" %}:</strong> {{ layer.poc.name}}</li>{% endif %}
        {% if layer.poc.email %}<li><strong>{% trans "Email" %}:</strong>  {{ layer.poc.email }}</li>{% endif %}
        {% if layer.poc.organization %}<li><strong>{% trans "Organization" %}:</strong> {{ layer.poc.organization}}</li>{% endif %}
        {% if layer.poc.position %}<li><strong>{% trans "Position" %}:</strong>: {{ layer.poc.position}}</li>{% endif %}
        {% if layer.poc.voice %}<li><strong>{% trans "Voice" %}:</strong>  {{ layer.poc.voice}}</li>{% endif %}
        {% if layer.poc.fax %}<li><strong>{% trans "Fax" %}:</strong> {{ layer.poc.fax}}</li>{% endif %}
        {% if layer.poc.delivery %}<li><strong>{% trans "Delivery" %}:</strong> {{ layer.poc.delivery}}</li>{% endif %}
        {% if layer.poc.area %}<li><strong>{% trans "Area" %}:</strong> {{ layer.poc.area}}</li>{% endif %}
        {% if layer.poc.zipcode %}<li><strong>{% trans "Zip Code" %}:</strong> {{ layer.poc.zipcode}}</li>{% endif %}
        {% if layer.poc.country %}<li><strong>{% trans "Country" %}:</strong> {{ layer.poc.country}}</li>{% endif %}
    </ul>
  {% endif %}
</p>
{% endif %}

{% if layer.attribute_names %}
<p> <strong>{% trans "Attributes" %}:</strong> 
    {{ layer.attribute_names|join:", " }}
</p>
{% endif %}

{% if layer.supplemental_information %}
<p> <strong>{% trans "Supplemental Information" %}:</strong> 
    {{ layer.supplemental_information }}
</p>
{% endif %}

{% if layer.data_quality_statement %}
<p> <strong>{% trans "Data Quality Statement" %}:</strong> 
    {{ layer.data_quality_statement }}
</p>
{% endif %}

{% if layer.geographic_bounding_box %}<p> <strong>{% trans "Bounding Box" %}:</strong> {{ layer.geographic_bounding_box }} </p>{% endif %}
{% if layer.metadata.crsOptions %}<p> <strong>{% trans "Native SRS" %}:</strong> {{ layer.metadata.crsOptions.0|default:_("No SRS specified.") }} </p>{% endif %}

</div>
{% endblock %}

{% block sidebar %}
<div id="sidebar" class="threecol">
    <h3> {% trans "Download" %} </h3>
    <p> <strong>{% trans "Data" %}: </strong>
        {% for extension, type, link in layer.download_links %}
            <a href="{{link}}">{{type}}</a>
        {% endfor %}
    </p>
    <p> <strong>{% trans "Metadata" %}: </strong>
        {% for mimetype, mdtype, link in layer.metadata_links %}
            <a href="{{link}}">{{mdtype}}</a>
        {% empty %}
            <em> {% trans "No metadata links provided for this data." noop %} </em>
        {% endfor %}
    </p>
    <h3>{% trans "Maps" %} </h3>
    {% if layer.maps %}
    <p>{% trans "The following maps use this data set" %}:
        <ul>
            {% for map in layer.maps %} 
            <li> <a href="{{map.get_absolute_url}}">{{map.title}}</a> </li>
            {% endfor %}
        </ul>
    {% else %}
        <p> {% trans "This layer is not currently used in any maps." %} </p>
    {% endif %}
    <p><a href="{% url geonode.maps.views.newmap %}?layer={{layer.typename}}">Create new map</a></p> 

    {% has_obj_perm user layer "maps.change_layer" as can_change %}
    {% has_obj_perm user layer "maps.delete_layer" as can_delete %}

    <h3> {% trans "Styles" %} </h3>
    <p> {% trans "The following styles are associated with this data set.  Choose a style to view it in the preview to the left.  Click on a style name to view or edit the style." %}
    <br/>
    <span class="styles-list">
        <input type="radio" name="style" id="{{layer.publishing.default_style.name}}" value="{{layer.publishing.default_style.name}}" checked="checked"/>
        <label for="{{layer.publishing.default_style.name}}" class="style-title"> {{ layer.default_style.name|title }} </label>
        <a href="{{ layer.default_style.body_href }}">SLD</a><br/>
    {% for style in layer.styles %} 
        <input type="radio" name="style" id="{{style.name}}" value="{{style.name}}"/>
        <label for="{{style.name}}" class="style-title"> {{ style.name|title }} </label>
        <a href="{{ style.body_href }}">SLD</a><br/>
    {% endfor %}
    </span>
    {% if user.is_authenticated and can_change %}
    {% trans "Default style:" %}
    <select name="default-style">
        <option value="{{layer.publishing.default_style.name}}" selected="selected">
          {{layer.publishing.default_style.name|title}}
        </option>
    {% for style in layer.styles %} 
        <option value="{{style.name}}"> {{ style.name|title }} </option>
    {% endfor %}
    </select><br/>
    <a href="javascript:showStyle()">Create new style</a>
    {% endif %}

    </p>



    {% if user.is_authenticated %}
    {% if can_change or can_delete or can_change_permissions %}

        <h3> {% trans "Manage" %} </h3>
        <ul>
			{% if user.is_authenticated %}
        {% if can_change %}
                <li><a href="?describe">{% trans "Update the description of this data" %}</a></li>
            	<li><a href="?update">{% trans "Upload a new version of this data" %}</a></li>
        {% endif %}
        {% if can_change_permissions %}
        <li><a href="{% url edit_layer_permissions layer.typename %}">{% trans "Edit Permissions" %}</a></li>
        {% endif %}
            {% if can_delete %}
				<li><a href="?remove">{% trans "Remove" %}</a></li>
			{% endif %}
			{% else %}
				<li>Please authenticate to update or remove layers</li>
			{% endif %}
        </ul>
    {% endif %}
    {% has_obj_perm user layer "maps.change_layer_permissions" as can_change_permissions %}
    {% if can_change_permissions %}
    <h3>{% trans "Permissions" %}</h3>
      <div id="permissions_form"></div>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

quality/templates/quality/layerRanking.html
{% extends "page_layout.html" %}
{% load i18n %}

{% block title %} {% trans "Browse Data" %} - {{ block.super }} {% endblock %}

{% block head %}
{% include "geonode/ext_header.html" %}
{% include "geonode/app_header.html" %}
{{ block.super }}
{% endblock %}

{% block main %}
<div class="twocol">

    <h2>This is the list of the layers in the sub-topic of interest</h2>
    <p>For each of them the total score, both weighted and unweighted, got from the GMES RDA Lot2 quality indicators, is shown in the table below</p>

	<p><strong>GMES Quality Assessment Results</strong></p>

	<table border="5" frame="vsides">
		<tr>
			<th align='left'>Layer title</th>
			<th align='left'>Unweighted score</th>
			<th align='left'>Weighted score</th>
		</tr>
		{% for layer, score, unWeightedScore in results %}
			<tr>
				<td align='left'><a href="{{"/data/"|add:layer.typename}}">{{layer.title}}</a></td>
				<td align='center'>{{unWeightedScore}}</td>
				<td align='center'>{{score}}</td>
			</tr>
		{% endfor %}
	</table>

<!--			<th>Indicator</th>
			<th>Score</th>

		<tr>
			<td>Geographic Extent</td>

		</tr>
		<tr>
			<td>Licensing and Constraints</td>
			<td align='center'>{{qualityRecord.licensingConstraint}}</td>
		</tr>
		<tr>
			<td>Scale Denominator</td>
			<td align='center'>{{qualityRecord.scaleDenominator}}</td>
		</tr>
		<tr>
			<td>Update</td>
			<td align='center'>{{qualityRecord.update}}</td>
		</tr>
		<tr>
			<td>Temporal Extent</td>
			<td align='center'>{{qualityRecord.temporalExtent}}</td>
		</tr>
		<tr>
			<td>Fitness for Use</td>
			<td align='center'>{{qualityRecord.fitness4Use}}</td>
		</tr>
		<tr>
			<td>Thematic Richness</td>
			<td align='center'>{{qualityRecord.thematicRichness}}</td>
		</tr>
		<tr>
			<td>Integration</td>
			<td align='center'>{{qualityRecord.integration}}</td>
		</tr>
		<tr>
			<td>Data Integrity</td>
			<td align='center'>{{qualityRecord.dataIntegrity}}</td>
		</tr>
		<tr>
			<td>Positional Accuracy</td>
			<td align='center'>{{qualityRecord.positionalAccuracy}}</td>
		</tr>
		<tr>
			<td>Thematic Accuracy</td>
			<td align='center'>{{qualityRecord.thematicAccuracy}}</td>
		</tr>
		<tr>
			<td>Completeness</td>
			<td align='center'>{{qualityRecord.completeness}}</td>
		</tr>
	</table>
-->
</div>
{% endblock %}

{% block sidebar %}
  {% block sidebar_info %}    
  {% endblock %}

{% endblock %}

quality/templates/quality/subtopics.html
{% extends "page_layout.html" %}
{% load i18n %}

{% block title %} {% trans "Browse Data" %} - {{ block.super }} {% endblock %}

{% block head %}
{% include "geonode/ext_header.html" %}
{% include "geonode/app_header.html" %}
{{ block.super }}
<script type="text/javascript">
Ext.onReady(function(){
{% autoescape off %}
  var submitForm = function() {
      Ext.query('#search_form form')[0].submit();
  };
  var searchButton = new Ext.Button({renderTo: 'submit_search', text: '{% trans "Search" %}',
                                     handler: submitForm});
  var searchInput = new Ext.form.TextField({applyTo: 'search_query', width: 350});
	
	var goButton = new Ext.Button({
		renderTo: 'ask_weights',
		text: 'Go!',
		handler: function(){window.location = "{%url geonode.maps.views.maps_search_page%}";}
	});
{% endautoescape %}
});
</script>
{% endblock %}

{% block main %}
<div class="twocol">

    <h2>This is the list of the data sub-topics available in the server</h2>
    <p>Please select your subtopic of interest in order to get the dataset of best quality!</p>

	<form action="/quality/ask4weights" method="GET">
		<fieldset>
			<legend>Available sub-topics</legend>
			{% for oneSub in allSubs %}
				{% if oneSub.layersubtopic_set.count > 0 %}
		    		<input type="radio" name="subtopic" value={{oneSub.pk}}/>{{oneSub.title}}
					<br>
				{% endif %}
			{% endfor %}
			<input type="submit" value="Next">
		</fieldset>
	</form>

</div>
{% endblock %}

{% block sidebar %}
  {% block sidebar_info %}    
  {% endblock %}

{% endblock %}